### ISSUE TITLE
Add Python 3 Support

### ISSUE THREAD

**Issue by troygrosfield** [areski/django-lets-go#1]
Pip install is failing for python 3.3.3 using django 1.6.1:

```
(py33_django16)➜  $ pip install switch2bill-common
Downloading/unpacking switch2bill-common
  Downloading switch2bill-common-2.8.5.tar.gz
  Running setup.py (path:/.virtualenvs/py33_django16/build/switch2bill-common/setup.py) egg_info for package switch2bill-common

Downloading/unpacking django-reusableapps==0.1.1 (from switch2bill-common)
  Downloading django-reusableapps-0.1.1.tar.gz
  Running setup.py (path:/.virtualenvs/py33_django16/build/django-reusableapps/setup.py) egg_info for package django-reusableapps
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/.virtualenvs/py33_django16/build/django-reusableapps/setup.py", line 2, in <module>
        from ez_setup import use_setuptools
      File "./ez_setup.py", line 97
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/.virtualenvs/py33_django16/build/django-reusableapps/setup.py", line 2, in <module>

    from ez_setup import use_setuptools

  File "./ez_setup.py", line 97

    except pkg_resources.VersionConflict, e:

                                        ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /.virtualenvs/py33_django16/build/django-reusableapps
Storing debug log for failure in /.pip/pip.log
```

**Comment by areski** [comment]
Yesterday release 2.9.1 has been free of dependencies, so give it a try and it should be fine
